### ISSUE TITLE
Could not find module `@ember/destroyable` imported from `ember-ref-bucket/utils/ref`

### ISSUE THREAD

**Issue by basz** [lifeart/ember-ref-modifier#358] opened 2020-08-20 12:57 UTC
Looks like that with the current ember-bootstrap#master I get this error.

```
Fatal Error: Could not find module `@ember/destroyable` imported from `ember-ref-bucket/utils/ref`
```

I've inspected .lock and am using v1.0.0 of ember-ref-modifier. ember-destroyable-polyfill also looks as installed.

(ember 3.20)

**Comment by basz** [comment] 2020-08-20 12:57
using yarn workspaces... maybe a hoisting issue?

**Comment by basz** [comment] 2020-08-20 13:03
Shouldn't that package be present in your package.json? https://github.com/lifeart/ember-ref-modifier/blob/master/package.json

**Comment by lifeart** [comment] 2020-08-20 16:09
@basz thank you for report! I think we should add ember-destroyable-polyfill as dependency, I will take care of it in a few hours

**Comment by basz** [comment] 2020-08-21 07:10
ping

(so sorry..., bs forms are broken in production :-) )

**Comment by lifeart** [comment] 2020-08-21 07:34
@basz, sorry for confusion, just checking, `ember-ref-bucket` has dependency `ember-destroyable-polyfill` https://github.com/lifeart/ember-ref-bucket/blob/master/package.json#L33

and `ember-ref-modifier` don't use destroyable api

**Comment by lifeart** [comment] 2020-08-21 07:35
looks like it may be an `node_modules` issue, try to reinstall it

**Comment by basz** [comment] 2020-08-21 08:24
Sorry, I was confusing with ember-ref-bucket with ember-ref-modifier... Reinstalled node_modules. same... 😕

**Comment by lifeart** [comment] 2020-08-21 08:26
@basz try to add `ember-destroyable-polyfill` into application `package.json`, is it solve issue?

**Comment by basz** [comment] 2020-08-21 08:52
Nope. Just tried it to add to the project workspace root package.json and/or application package.json. No luck.

But, If I switch back to "ember-bootstrap": "kaliber5/ember-bootstrap#pull/1183/head", (avoiding this package) and do `import { registerDestructor } from '@ember/destroyable';` in my application route the error is also "Could not find module `@ember/destroyable` imported from `@plhw-lab/lab-plhw/pods/application/route`".

So I guess it is *not* related to these packages...

**Comment by lifeart** [comment] 2020-08-21 08:57
@basz looks like bug in https://github.com/ember-polyfills/ember-destroyable-polyfill, could you try to create repo with minimal reproduction?

**Comment by basz** [comment] 2020-08-21 09:18
Think I found it ember-destroyable-polyfill requires ember-cli-babel ^7.22.1. I can now import it from my application... 

However `ember-ref-bucket/utils/ref` still can't... hmmm...

**Comment by basz** [comment] 2020-08-21 09:20
Could these be an issue?

https://github.com/lifeart/ember-ref-modifier/blob/master/package.json#L30
https://github.com/lifeart/ember-ref-bucket/blob/master/package.json#L31

edit:

because they don't match babel 7.22.1+. A bit of guessing here :-)

(from .lock)
```
ember-ref-bucket@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/ember-ref-bucket/-/ember-ref-bucket-1.0.0.tgz#e310388d8ec698c3686b4350275af28d05481599"
  integrity sha512-Kfnzx9XMiiyDGFxFCVH9VWfLMFBRlxgimdB1PKfx9zQUmNkiiM+N1MOXCN3CnDyJ+Azbfz6SCPcOuOEPuYWTxA==
  dependencies:
    ember-cli-babel "^7.21.0"
    ember-cli-htmlbars "^5.2.0"
    ember-destroyable-polyfill "^2.0.1"

ember-ref-modifier@^1.0.0:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/ember-ref-modifier/-/ember-ref-modifier-1.0.1.tgz#aeca56798ebc0fb750f0ccd36e86d667f5b1bc44"
  integrity sha512-qmEFY/4WOWWXABRWvX50jLPleH30p/LPLUXEvaSlIj41F23e3Vul91IqZ1PFdw1Rxpkb8DHWO5BRchN8vnz4+Q==
  dependencies:
    ember-cli-babel "^7.20.5"
```

**Comment by lifeart** [comment] 2020-08-21 09:57
it may be, https://github.com/lifeart/ember-ref-bucket/pull/3 created

**Comment by lifeart** [comment] 2020-08-21 11:43
fixed by https://github.com/lifeart/ember-ref-bucket/pull/3

**Closed as completed by lifeart** 2020-08-21 11:43 UTC
